print("¿cuál es tu canción favorita?")
titulo_cancion = input("Título de la canción: ")
Artista = input("Artista: ")
Album = input("Álbum: ")
Anyo_de_lanzamiento = input("Año de lanzamiento: ")
Duracion_cancion = input("Duración en segundos¨: ")
tiene_videoclip = input("¿Tiene videoclip?: ")


print("Tu canción favorita es: ", titulo_cancion)
print("artista : ", Artista)
print("álbum: ", Album)
print("Año de lanzamiento: ", Anyo_de_lanzamiento)
print("duranción de la canción: ", Duracion_cancion,)
print("¿Tiene videoclip? ", tiene_videoclip)

print("¿Cuál es la canción que menos te gusta?")
titulo_cancion_no_gusta = input("Título de la canción: ")
Artista_no_gusta= input("Artista: ")
Album_no_gusta= input("Álbum: ")
Anyo_de_lanzamiento_no_gusta = input("Año de lanzamiento: ")
Duracion_cancion_no_gusta = input("Duración en segundos¨: ")
tiene_videoclip_no_gusta = input("¿Tiene videoclip?: ")

print("Tu canción que menos te gusta es: ", titulo_cancion_no_gusta)
print("artista : ", Artista_no_gusta)
print("álbum: ", Album_no_gusta)
print("Año de lanzamiento: ", Anyo_de_lanzamiento_no_gusta)
print("duranción de la canción: ", Duracion_cancion_no_gusta,)
print("¿Tiene videoclip? ", tiene_videoclip_no_gusta)
