print("¿cuál es tu canción favorita?")
titulo_cancion = input("Título de la canción: ")
Artista = input("Artista: ")
Album = input("Álbum: ")
Ano_de_lanzamiento = input("Año de lanzamiento: ")
Duracion_cancion = input("Duración en segundos¨: ")
tiene_videoclip = input("¿Tiene videoclip? (Verdadero/Falso): ")

print("Tu canción favorita es: ", titulo_cancion)
print("artista : ", Artista)
print("álbum: ", Album)
print("Año de lanzamiento: ", Ano_de_lanzamiento)
print("duranción de la canción: ", Duracion_cancion,)
print("¿Tiene videoclip? ", tiene_videoclip)

print("¿Cuál es la canción que menos te gusta")
titulo_cancion = input("Título de la canción: ")
Artista = input("Artista: ")
Album = input("Álbum: ")
Ano_de_lanzamiento = input("Año de lanzamiento: ")
Duracion_cancion = input("Duración en segundos¨: ")
tiene_videoclip = input("¿Tiene videoclip? (Verdadero/Falso): ")

print("Tu canción que menos te gusta es: ", titulo_cancion)
print("artista : ", Artista)
print("álbum: ", Album)
print("Año de lanzamiento: ", Ano_de_lanzamiento)
print("duranción de la canción: ", Duracion_cancion,)
print("¿Tiene videoclip? ", tiene_videoclip)
